### ISSUE TITLE
Cannot log messages that aren't string

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#100]
`self.log.info(None)` throws a "schema" error in QML.

I remembered we talked about this @tokejepsen, but I can't seem to dig up that conversation nor issue. If you know where it is, could you link to it here?

**Comment by tokejepsen** [comment]
Think it was somewhere in gitter, but can't find it.

Yeah, main thing is all non-strings throws an error.

**Comment by tokejepsen** [comment]
This can be closed:)

**Comment by mottosso** [comment]
Doesn't it still throw an error?

**Comment by tokejepsen** [comment]
Tested it in Nuke, and it doesn't throw an error anymore.

**Comment by mottosso** [comment]
Ah, so it is as they say; "time fixes all bugs". :)

Looks like this has indeed been fixed, [here](https://github.com/mottosso/pyblish-qml/commit/40a08d9bd1c221af6ac76de40638a60faa0f638b).

Test case.

```python
import pyblish.api

class Collector(pyblish.api.Collector):
    def process(self, context):
        t = type("test", (object,), {})
        t1 = t()
        self.log.info(t1)
        self.log.info(None)

pyblish.api.register_plugin(Collector)

import pyblish_maya
pyblish_maya.show()
```

Case closed!
