### ISSUE TITLE
Context label

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#102]
With the visualisation of the context in the UI, we could have a label on the context as well, similar to plugins.

The user would set the context label in a selector similar to;

```python
import pyblish.api


@pyblish.api.log
class SelectContextLabel(pyblish.api.Selector):
    """ Sets the context label
    """

    def process(self, context):
        context.set_data('label', 'Project X / Shot Y')
```

**Comment by mottosso** [comment]
Having a look at implementing this now, and realised what I think we talked about before; what happens when 2 plug-ins set `label`?

Did we ever find a more clean-cut solution to this?

**Comment by tokejepsen** [comment]
> Did we ever find a more clean-cut solution to this?

Don't think we did, but I also don't think there is one. Last evaluated plugin, and then its up to the user to debug from there.

**Comment by mottosso** [comment]
Mm, I also discovered another logical problem.

What if Conform sets the name? Before that point, the Context will already be in the GUI. We would need the GUI to re-evaluate the context name after each plug-in, adding to execution time and complexity.

Here's a quick alternative.

```python
import pyblish.api
pyblish.api.set_context_name("label', 'Project X / Shot Y")
```

This would happen before any publishing, such as in the `userSetup.py` of Maya.

Thoughts?

**Comment by tokejepsen** [comment]
> What if Conform sets the name?

I don't see any use case for this. I like to think of this action as gathering data from the scene similar to creating instances.

> Thoughts?

Its a possibility, but for easy access for users I would still have it in a selector.

**Comment by mottosso** [comment]
Ok, I think I've got something that could work for this, and for future configuration of the GUI, along with  when we start to persist settings across runs, such as Window size and position, themes, colors, fonts, and what not.

```python
from pyblish_qml import settings
settings.ContextLabel = "The World"
settings.WindowTitle = "Jurassic World | Shot 1 | Animation"
```

This will need to be set *before* pre-launching QML, so in your `userSetup.py` for Maya and similar files for other hosts.

**Comment by mottosso** [comment]
> I don't see any use case for this.

There aren't any (now), but the fact that it's possible adds a number of question marks that I'd rather not have. Especially when dealing with many extensions provided by other users, how do you know which one(s) are messing with the settings?

**Comment by tokejepsen** [comment]
> how do you know which one(s) are messing with the settings?

I guess you don't know, but you could also say the same thing about the ```userSetup.py```, as this could be a studio wide and one local at the same time.

> This will need to be set before pre-launching QML, so in your userSetup.py for Maya and similar files for other hosts.

Are there other technical issues behind this, or is it a matter of logistics?
From a file management point of view, I would rather work with pyblish plugins than have to implement what is ```userSetup.py``` for other hosts. Having one selector for multiple hosts, beats having ```userSetup.py```, ```menu.py``` etc.

**Comment by mottosso** [comment]
> I guess you don't know, but you could also say the same thing about the userSetup.py, as this could be a studio wide and one local at the same time.

But you are always given a choice about whether or not to roll your own `userSetup.py`, or use the default one(s). The default ones are really included for convenience, I'd expect any serious environment to handle their own setup/teardown of host tools.

> Are there other technical issues behind this, or is it a matter of logistics?

Both. And I'm trying to keep in mind more use-cases than this one in particular. If you needed to, you could make a selector for your Pyblish QML settings.

```python
import pyblish_qml.settings

class SelectQMLSettings(pyblish.api.Selector):
  def process(self):
    pyblish_qml.settings.ContextLabel = "My Label"
```

The important thing is that it isn't an isolated feature for one specific problem, and that it is possible to take full control over where global settings (it is global after all) are truly defined.

**Comment by tokejepsen** [comment]
> If you needed to, you could make a selector for your Pyblish QML settings.

If you can do this as well as the ```userSetup.py```, that would be great:)

**Comment by mottosso** [comment]
I wrote this before re-reading your comment, probably not what you meant but posting anyway because of it's madness. :)

```python
import os
import pyblish.api

class SelectUserSetupPy(pyblish.api.Selector):
  def process(self):
    any_path_on_pythonpath = os.environ["PYTHONPATH"].split(";", 1)[0]
    with open(os.path.join(any_path_on_pythonpath, "userSetup.py"), "w") as f:
      f.write("\n".join(["import pyblish_maya", "pyblish_maya.setup()"]))
```

**Comment by tokejepsen** [comment]
> I wrote this before re-reading your comment, probably not what you meant but posting anyway because of it's madness. :)

Wow, too mad for me:)

**Comment by BigRoy** [comment]
> This will need to be set before pre-launching QML, so in your userSetup.py for Maya and similar files for other hosts.

Isn't that actually rather inconvenient? What happens if you open another scene/asset in your current Maya session? `userSetup.py` doesn't get triggered. Nor does the pyblish GUI gets restarted, yet it's loaded from cache. Or is loading a cached instance also a reason to update the UI?

```python
import pyblish_qml.settings

class SelectQMLSettings(pyblish.api.Selector):
  def process(self):
    pyblish_qml.settings.ContextLabel = "My Label"
```
This seems fine to me. It seems less intuitive than just setting `label` as data on the Context, but if it's GUI related only then this is definitely fine.

I guess nothing would be stopping anyone from doing:

```python
import pyblish_qml.settings

class SelectQMLSettings(pyblish.api.Selector):
    order = pyblish.api.Selector.order + 0.1
    def process(self, context):
        label = context.data('label') or 'Context'
        pyblish_qml.settings.ContextLabel = label
```

**Comment by mottosso** [comment]
I can see what you mean, it would be ideal to have the option of naming it be sensitive to the current environment when it comes to give it names involving the current task, shot or asset etc.

If not via `context.set_data`, and not via `settings.ContextLabel`, what can we do?

**Comment by tokejepsen** [comment]
> If not via context.set_data, and not via settings.ContextLabel, what can we do?

Think @BigRoy was liking ```context.set_data``` similar to instances?

**Comment by mottosso** [comment]
Yes, but for the reasons already given, it's not a great option.

**Comment by tokejepsen** [comment]
So when opening other scenes in Maya, this selector doesn't refresh the label?

```python
import pyblish_qml.settings

class SelectQMLSettings(pyblish.api.Selector):
  def process(self):
    pyblish_qml.settings.ContextLabel = "My Label"
```

**Comment by mottosso** [comment]
I'm having a look at making it possible to alter things at run-time now, in which case that should work.

**Comment by BigRoy** [comment]
Could the `pyblish_qml.settings` attributes be setter methods that trigger an automated update?

**Comment by mottosso** [comment]
> Could the pyblish_qml.settings attributes be setter methods that trigger an automated update?

I did give that a go, and though it worked, it's got complex real fast.

I think I've got a better option, which technically means to send across the settings each time the GUI is requested to be shown.

**Comment by mottosso** [comment]
Ok, have a look and let me know what you think.

- https://github.com/pyblish/pyblish-qml/pull/104

**Comment by tokejepsen** [comment]
Since its a probation support, are you holding off on putting it into pyblish-win?

**Comment by mottosso** [comment]
No, I'll put it in. If it disappears, it won't be until a few versions down. Dunno yet, giving the concept of "probation" a try, and expect to discover when a good time to either keep or cut shows up. Kind of like the opposite of "deprecated", but with a questionmark.

The idea is to not lock ourselves in until we know for sure it's a valuable feature.

For now, use it, but keep in mind that we might cut it in favour of a better alternative down the line. Unless we don't find one, in which case it's a keeper.

**Comment by tokejepsen** [comment]
Since its a probation support, are you holding off on pushing it to pyblish-win?

**Comment by mottosso** [comment]
Implemented since a few versions back, and seems stable.
