### ISSUE TITLE
Instance in reports by default

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#103]
Having the instance name operated on in all messages logged, would make it easier to debug when focusing on one plugin with the perspective. The area for the instance is highlighted below;

![capture](https://cloud.githubusercontent.com/assets/1860085/8256975/6a46e646-16a2-11e5-95bf-ead77833660e.PNG)

**Comment by mottosso** [comment]
Thanks @tokejepsen

**Comment by mottosso** [comment]
Implemented in [0.2.11](https://github.com/pyblish/pyblish-qml/releases/tag/0.2.11)
