### ISSUE TITLE
GUI hangs on load with custom Plugin.

### ISSUE THREAD

**Issue by BigRoy** [pyblish/pyblish-qml#110]
For example the plug-in below will make the GUI never pass the rotating circle. The GUI remains in the *Not Ready* state.

```python
import pyblish.api

class ReportBuggy(pyblish.api.Plugin):
    def process(self, context):
        pass
```

The following would only load the GUI up to the Validators (or actually up to the order). So the GUI really hangs on this custom Plugin.

```python
import pyblish.api

class ReportBuggy(pyblish.api.Plugin):
    order = pyblish.api.Validator.order + 0.1

    def process(self, context):
        pass
```

Tested on Windows 7 x64 running within Maya with `pyblish-win` version 1.0.8.

**Comment by mottosso** [comment]
Thanks, this was a bug from the latest release.
