### ISSUE TITLE
Configurable Client Ports

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#114]
### Goal

Enable users to customise which ports should be used to communicate with Pyblish RPC.

### Motivation

Currently, clients launch at 6001 and increment from there. Next client occupies 6002, 6003 and so forth. However, it's likely that this series of ports may already be in use. As discussed in this [forum thread](http://forums.pyblish.com/t/publish-from-two-hosts-simultanously/126/59).

### Implementation

During host set-up, provide an option to customise this port.

```python
import pyblish_maya
pyblish_maya.setup(port=9001)
```

Which means integration in these cases cannot rely solely on environment variables; i.e. the supplied `userSetup.py` in case of Maya. But will instead need to provide their own tailored `userSetup.py`.

##### Globally Used Ports

If `psutil` is available, Pyblish also take into consideration ports in use by other processes on your local system. It is recommended that you install it, but may already be provided with your distribution of Pyblish, such as pyblish-win.

Otherwise, it's possible that you may publish from a few hosts, but eventually encounter a limit of possible Pyblish-enabled hosts open at the same time.

**Comment by tokejepsen** [comment]
Can we not use environment variables for this?

**Comment by tokejepsen** [comment]
Would be great to use a single environment variable ```PYBLISHPORT```, that will be used across all integrations.

**Comment by mottosso** [comment]
I'll have a look.

**Comment by mottosso** [comment]
Having trouble with this, it will have to wait until the next update.

The trouble is synchronising the two processes; your host and the Pyblish QML Python interpreter. Providing an environment variable when launching say Maya should "pass it on" to the Pyblish QML interpreter, but it doesn't look like it is, or I'm missing something else.

It's difficult to debug currently and simplified debugging is on the way. Until then, hope this will suffice!

Also, the default `first_port` got changed to `9001`, so you shouldn't need to do much.

**Comment by tokejepsen** [comment]
> Also, the default first_port got changed to 9001, so you shouldn't need to do much.

Ahh, fair enough. That was what I needed here:)
