### ISSUE TITLE
Validate

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#115]
### Goal

Enable users to run validation only, to evaluate context without actually publishing.

**Comment by tokejepsen** [comment]
Would this not just be having only validators for plugins?

**Comment by mottosso** [comment]
This would run all Validators, even when you have other plug-ins available. It can be useful when you are only looking for a report while working.

Here's an example.

![untitled](https://cloud.githubusercontent.com/assets/2152766/9195786/78adbbac-401d-11e5-850d-2477750b61c2.gif)

**Comment by tokejepsen** [comment]
Ahhh, I see.

**Comment by BigRoy** [comment]
How does it know up to where to run the processes when using custom ordered plug-ins?

I think it might be nice to have the Flask button to represent a 'Run till order X' where right-clicking it gives you a drop-down menu of possible orders. Possibly highlighting the processes in the UI as you hover over the options.

This way it could run "Up to Validation", but also "Up to Report" if you have custom reporting plug-ins?

**Comment by mottosso** [comment]
The plug-ins to be run are those that pass this test.

```python
import pyblish.api
from pyblish.plugin import inrange

class MyPlugin(pyblish.api.Plugin):
  order = pyblish.api.Validator.order + 0.1

if inrange(MyPlugin.order, base=pyblish.api.Validator.order):
  # run it
```

Validators always ranges from 1, plus/minus 0.5.

**Comment by mottosso** [comment]
> This way it could run "Up to Validation", but also "Up to Report" if you have custom reporting plug-ins?

I don't really see a usecase for that. Orders aren't artist-facing, but highly internal to the development of plug-ins.

It also won't transfer to when we start using graphs. Orders are an implementation detail, for now.

**Comment by BigRoy** [comment]
> It also won't transfer to when we start using graphs. Orders are an implementation detail, for now.

Fair enough. Just checking what the conditions are.

**Comment by mottosso** [comment]
No problem Roy, it's good that you ask. Sorry to be short! A lot of juggling at the moment, trying to get things out of the way quickly. Perhaps a bit too quickly.

**Comment by mottosso** [comment]
Implemented since a few versions back!
