### ISSUE TITLE
Window open after host dies

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#120]
The QML window shouldn't remain open when the currently active host stops sending heartbeats.

**Comment by BigRoy** [comment]
This is likely resolved since 1.0.0 release. If not maybe we need to elaborate the problem some more.

**Comment by mottosso** [comment]
It's only resolved in Maya, so far.

Odds are we'll have to implement a similar mechanism for other hosts, which is to put in a callback that quits QML on host exit. In Maya, this [has been implemented](https://github.com/pyblish/pyblish-qml/blob/60b7bad40c4b19e3a3a5bb56831803d6d084e016/pyblish_qml/host.py#L223) as a `scriptJob`. Nuke and others may have a similar feature.

**Comment by BigRoy** [comment]
For Qt based hosts could we connect it to the `aboutToQuit` signal of the host Application?

http://doc.qt.io/qt-5/qcoreapplication.html#aboutToQuit

```python
from Qt import QtWidgets

QtWidgets.QApplication.instance().aboutToQuit.connect(function_to_close_QML)
```

**Comment by mottosso** [comment]
That's a good idea!
