### ISSUE TITLE
Quick Toggles

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#135]
**Goal**

Quickly toggle multiple instances.

**Motivation**

Publishing with more than 3 instances that aren't wanted, and needing untoggling, can quickly become tedious. Especially when resetting the publish after validation, resets the toggle states.

**Implementation**

The idea is to have a ```toggle_all``` checkbox for each instance family, as illustrated below for the ```deadline.render``` family.

![d2bd9f146c94be1092e84c1466f45482584a8354_1_349x500](https://cloud.githubusercontent.com/assets/1860085/11847401/13549b84-a415-11e5-9fd2-da675be8192b.png)
![7ee4e1ebe756f4639f186ae221738cb2ee0c37be_1_349x500](https://cloud.githubusercontent.com/assets/1860085/11847400/13507356-a415-11e5-8cbc-b3cabf70df64.png)

**Comment by mottosso** [comment]
Referencing this one so it doesn't get lost.
- https://github.com/pyblish/pyblish-qml/issues/26

Your one is better, because it has pictures. :)
