### ISSUE TITLE
Instance does not have "families" property

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#136]
The features of having multiple families per instance is not represented in the item model; https://github.com/pyblish/pyblish-qml/blob/master/pyblish_qml/models.py#L47

**Comment by mottosso** [comment]
Thanks Toke, this needs to be added.

**Comment by mottosso** [comment]
It just occurred to me that even though the information is not available in QML, the feature itself should still work, as the "check" for family compatibility is handled in the core library, not the GUI.

- [See here](https://github.com/pyblish/pyblish/blob/0fcf37a0b251f811f1071c858b723dc5065983a8/pyblish/logic.py#L288)

At first I thought this would have meant that the feature was incomplete, but it looks like just some missing (and unused) data.

It might still be a good idea to add it though, but only if it's needed by something (more data means less performance). Leaving this open for now, if you had a specific need for it @tokejepsen, let's narrow that down.

**Comment by tokejepsen** [comment]
> It might still be a good idea to add it though, but only if it's needed by something (more data means less performance). Leaving this open for now, if you had a specific need for it @tokejepsen, let's narrow that down.

We can have a look when I make a PR of #135. Everything is working, so we probably don't need to worry about this for now.
