### ISSUE TITLE
Clicking section for plug-ins has no effect

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#139]
In [a recent update](https://github.com/pyblish/pyblish-qml/pull/138), clicking sections was introduced. But only for instances. We'll need to either disable feedback for plug-ins, or add support there as well.

![](https://cloud.githubusercontent.com/assets/2152766/11951208/e9510b4e-a886-11e5-9ef2-6edc78dae1cb.gif)

**Comment by tokejepsen** [comment]
The main reason why I opted not to have any functionality on plugins were because you can't toggle collectors. Also the current logic doesn't work for ```Other``` plugins.

**Comment by mottosso** [comment]
Ah, gotcha.

Better make a note of these things in either the PR or comments in the code so we can stand on each others shoulders. I assumed you simply missed it and thought I'd help out filling it in.

Personally, I don't mind it being clickable but nothing happening, I think the result of nothing happening is enough to communicate that it does nothing. If we one day plan on adding support for it, it might be a good idea to keep the functionality there, instead of adding logic into temporary code.

**Comment by tokejepsen** [comment]
> Personally, I don't mind it being clickable but nothing happening, I think the result of nothing happening is enough to communicate that it does nothing. If we one day plan on adding support for it, it might be a good idea to keep the functionality there, instead of adding logic into temporary code.

We could also have the collectors checkboxes being true. This way the collectors are acting the way as the rest of the UI from the user perspective, ei. that not optional plugins can't be toggled.

**Comment by tokejepsen** [comment]
Then we just need a small amount of code for the ```Other``` logic.

**Comment by mottosso** [comment]
True means it'll get run when you hit "Publish" though. Since we're talking about changing their appearance, how about they don't have a checkbox at all?

> Then we just need a small amount of code for the Other logic.

Do you mean it would uncheck even mandatory plug-ins as it is now? The logic might be able to simply look for `optional` in the item, and do nothing for those that are `False` or don't have the property, such as instances.

**Comment by tokejepsen** [comment]
> how about they don't have a checkbox at all?

I like it:)

> Do you mean it would uncheck even mandatory plug-ins as it is now?

No, I meant that the current logic looks at the item verb and compares against the section label. This doesn't work for the ```Other``` section of plugins.

**Comment by tokejepsen** [comment]
> how about they don't have a checkbox at all?

Only problem would be how to indicate success and failure on those plugins, since its using the checkbox color for this. Probably better left for another issue altogether.

**Comment by mottosso** [comment]
> Only problem would be how to indicate success and failure on those plugins

Ah, yeah. I was also thinking of showing them processing, like the other plug-ins do such that error and progress would get better reflected in the GUI. Right now, the GUI is blank until they are all done.

But yes, a better talk for a separate issue.

> No, I meant that the current logic looks at the item verb and compares against the section label. This doesn't work for the Other section of plugins.

I'm looking at this now..

- [https://github.com/pyblish/pyblish-qml/blob/master/pyblish_qml/control.py#L370](https://github.com/pyblish/pyblish-qml/blob/dfbc79b60dfca8aa1d94f9f19aaf1241b1536f00/pyblish_qml/control.py#L370)

But can't quite figure out why this doesn't work as is?

**Comment by tokejepsen** [comment]
> But can't quite figure out why this doesn't work as is?

Ahh, it does actually work:) I just got confused when nothing was happening with the ```Other``` plugins, but they are all non-optional. Doh!

**Comment by tokejepsen** [comment]
Just need to add the ```onClicked``` to the plugin section delegate, which is the same the instance section delegate, so that could happen in the ```SectionItem.qml```?

**Comment by mottosso** [comment]
Nice!

> Just need to add the onClicked to the plugin section delegate, which is the same the instance section delegate, so that could happen in the SectionItem.qml?

Ideally, `SectionItem` would be this dumb (but reusable) building block with no hard-coded logic inside of it. Instead, we can put the logic at the top level. If you look at where it's currently used in Overview.qml, I think it should start to make sense.

- [https://github.com/pyblish/pyblish-qml/blob/master/pyblish_qml/qml/Overview.qml#L86](https://github.com/pyblish/pyblish-qml/blob/dfbc79b60dfca8aa1d94f9f19aaf1241b1536f00/pyblish_qml/qml/Overview.qml#L86)

You can think of it as being subclassed, every time you instantiate it.

**Comment by tokejepsen** [comment]
Cool, I'll send a PR now for this.
