### ISSUE TITLE
Closing host while the interface is open

### ISSUE THREAD

**Issue by davidmartinezanim** [pyblish/pyblish-qml#14]
At the moment, if the interface is open and you close the host, the interface will remain open but it will lose the connection with the host. I think that in those situations, we should either close the interface or provide some kind of feedback to the user so he can hook up the interface with other currently active hosts.

**Comment by mottosso** [comment]
This has been implemented in the integration.

**Comment by mottosso** [comment]
Fully implemented in Pyblish QML as of 0.2.6; if `psutil` is installed, it will kick in automatically.

```bash
$ pip install psutil
```
