### ISSUE TITLE
Plugin file path in Perspective

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#142]
Having multiple development environments can quickly become confusing, especially where plugins are located on disk.

Here are some options:

![basic_info](https://cloud.githubusercontent.com/assets/1860085/11954009/bf794686-a89c-11e5-894c-fa59bdcb1e4d.jpg)

![filepath](https://cloud.githubusercontent.com/assets/1860085/11954008/bf78fcb2-a89c-11e5-9d2d-b5f1c0314a9b.jpg)

If the plugin is in memory, this would be good to indicate in the path as well.

**Comment by mottosso** [comment]
I know we talked about this somewhere.. good there's an issue for it, definitely something to add.
