### ISSUE TITLE
Explicitly request data from pyblish-rpc

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#144]
Currently the data exposed from pyblish-rpc is getting added via a data member from [pyblish-rpc](https://github.com/pyblish/pyblish-rpc/blob/436ea351387c5159acb0fc06120d341dc97a6df7/pyblish_rpc/formatting.py#L306). This makes it difficult to see what data is exposed in pyblish-qml.

The solution is to explicitly list what data gets exposed to pyblish-qml in pyblish-qml, similar to;
```python
for member in ["pre11", "name", "label", ...]:
  item[member] = plugin[member]
```

**Comment by mottosso** [comment]
If you select a line of code, and then hit the `Y` key, you'll get a permanent link to that line. Otherwise, the line might change number when we merge.

I've gone ahead and updated the link for you!

**Comment by tokejepsen** [comment]
Cheers:)
