### ISSUE TITLE
Plugins display when no compatible families are present

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#154]
**Reproducible**
```python
import pyblish.api
import pyblish_integration


class CollectInstance(pyblish.api.Collector):
    
    def process(self, context):
        
        context.create_instance("Some Instance", family="someFamily")

class ValidatorWithoutInstance(pyblish.api.Validator):
    
    families = ["otherFamily"]
    
    def process(self, instance, context):
        
        pass


pyblish.api.register_plugin(CollectInstance)
pyblish.api.register_plugin(ValidatorWithoutInstance)

pyblish_integration.show()
```

The problem is when you have ```context``` as inputs to the validators process method. Removing it will give expected behaviour, as in not showing the validator in the GUI.

**Comment by tokejepsen** [comment]
I don't know whether this is a bug worth fixing. It seems to be me, that users could easily fix the issue by not using ```context``` as an input when the plugin is instance based. So its more of a workflow issue than fixing it in code.

Secondly I'm guessing this won't be an issue when there are [explicit plugins](https://github.com/pyblish/pyblish-base/issues/242).

**Comment by mottosso** [comment]
I think it's worth fixing if it's changed since before. Ideally there shouldn't be any change that breaks previous behaviour.

Can you pin-point when this worked differently than how it works currently? Or was this something you happened to notice just now?

**Comment by tokejepsen** [comment]
> I think it's worth fixing if it's changed since before. Ideally there shouldn't be any change that breaks previous behaviour.

Cool, I've got a fix ready tomorrow. Just didn't get to commit it before leaving.

> Can you pin-point when this worked differently than how it works currently? Or was this something you happened to notice just now?

Can't remember when, but after doing the fix and looking back the commit, I think the problem arose [here](https://github.com/pyblish/pyblish-qml/commit/7c279e110e35ffbb7d59336d34dc7b9ea1db784b#diff-ac156cba73ac1ef385b357bbfc21d258R617)

**Comment by mottosso** [comment]
Having a look at this now..

**Comment by mottosso** [comment]
Ok, this was a simple logic error.

Fix coming up here:

- https://github.com/pyblish/pyblish-qml/pull/158
