### ISSUE TITLE
Actions Availability

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#172]
If you have an action working on failed instances, the appearence of when you can right-click and select the action isn't consistent.

Here is a test for this case:

```python
import pyblish.api
import pyblish_integration


class SelectMany(pyblish.api.ContextPlugin):
    order = pyblish.api.CollectorOrder
    def process(self, context):
        for name in ("A", "B", "C"):
            instance = context.create_instance(name)
            instance.set_data("family", "myFamily")


class FailureAction(pyblish.api.Action):
    on = "failed"


class ValidateFailA(pyblish.api.InstancePlugin):
    order = pyblish.api.ValidatorOrder
    families = ["myFamily"]
    actions = [FailureAction]
    def process(self, instance):
        assert str(instance) != "A"


class ValidateFailBC(pyblish.api.InstancePlugin):
    order = pyblish.api.ValidatorOrder
    families = ["myFamily"]
    actions = [FailureAction]
    def process(self, instance):
        assert str(instance) == "A"


pyblish.api.deregister_all_plugins()
pyblish.api.register_plugin(SelectMany)
pyblish.api.register_plugin(ValidateFailA)
pyblish.api.register_plugin(ValidateFailBC)
pyblish_integration.show()
```

The test basically shows that the first instance in the execution list, is the determining factor for whether the action is available or not.
In the test the action should be available for both validators, but is only available for ```ValidateFailA```, because it fails the first instance in the execution list.
It does not have the action available for ```ValidateFailBC```, because instance ```A``` succeeds and instance ```B``` and ```C``` fails.

**Comment by BigRoy** [comment]
Was about to post about this as it has been confusing both the artists (and myself!) as to why and when this was happening. Thanks for the brief explanation and pinpointing where the issue was coming from.

Any idea where to look in the code to get this fixed?

**Comment by mottosso** [comment]
Here's the if-statement in control over when actions are visible and not.

- https://github.com/pyblish/pyblish-qml/blob/90db447049b17143283c60f08397f439ec4be236/pyblish_qml/control.py#L321

**Comment by BigRoy** [comment]
Was looking there but couldn't really find (or debug) where the root of the proble was. Anyway, would be great to have this confusing issue solved.

**Comment by tokejepsen** [comment]
Sorry, been trying to get some time to fix this, but it's running away from me. Got kinda stuck on getting a quick setup for restarting qml for development.

**Comment by mottosso** [comment]
Hey @tokejepsen I added an example to setup a custom debug mode here:

- https://pyblish.gitbooks.io/developer-guide/content/getting_started_with_pyblish_qml.html#custom-debug-mode

**Comment by tokejepsen** [comment]
Thank you @mottosso!

**Comment by tokejepsen** [comment]
Looks like this is entirely my fault:s

When introducing the Actions icon, this code was merged; https://github.com/pyblish/pyblish-qml/blob/a11c152aa40aa277cee648fcbc80f581893f5951/pyblish_qml/models.py#L427-L440. The problem is that ```actions = item.actions``` modifies the original actions list, and doesn't take a copy of it to work with. Should be ```actions = list(item.actions)```.

Can quickly make a PR with just the code fix, but a test will take a lot longer.

**Comment by BigRoy** [comment]
Thanks! Both ways is fine for me, I can just quickly alter it locally. Yet I do think the faster the fix is in the better. Lets PR and keep the issue open regarding building a test for it?

**Comment by tokejepsen** [comment]
PR ready

**Comment by tokejepsen** [comment]
Can we close this?
