### ISSUE TITLE
Black font color in Maya

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#18]
Cannot reproduce, occured for @davidmartinezanim

![image](https://cloud.githubusercontent.com/assets/2152766/5245227/96f3c802-7950-11e4-9000-b260929ddceb.png)

**Comment by tokejepsen** [comment]
This is happening in Nuke on Windows as well

**Comment by mottosso** [comment]
This seems to be happening whenever the communication between GUI and host is somehow interrupted. @tokejepsen You mentioned you were getting an error about not being able to serialize to JSON, does this still happen when you aren't getting this message?

**Comment by tokejepsen** [comment]
ok, maybe we should see what happens when we have a correct validation from Nuke without errors.

**Comment by mottosso** [comment]
The error is most likely coming from pre-launch of the GUI, or do  you mean the font color changes while publishing?

**Comment by tokejepsen** [comment]
no, the font color is the same throughout, but was some errors when trying to validate which I posted in gitter.
