### ISSUE TITLE
checkbox's are unclear

### ISSUE THREAD

**Issue by larsbijl** [pyblish/pyblish-qml#187]
the current implementation of the checkbox though pretty doesn't match the metal model of most users. for example.

![checkboxes](https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0Bzhp5Z4wHba3cy1pRXJxY2dnN28/components_switches_check4.png)

this make use of a standard convention that is know by all web users.

with the current implementation it get's mistaken for flags or just status information.

**Comment by mottosso** [comment]
Like it!

**Comment by larsbijl** [comment]
my current solution.

![screenshot-3](https://cloud.githubusercontent.com/assets/285658/15045982/6eb94734-12d5-11e6-832f-3c6c4940b9f6.png)

**Comment by mottosso** [comment]
Getting there!

Perhaps keep the fill in the background, scale down the icon (with size: 8 to 10) or scale up the border, and make it the same color as the background to make it appear as a cut-out, like in the initial reference? Could also restore the opacity to get rid of the doubling up of opacity where checkbox and border meet.

**Comment by larsbijl** [comment]
![screenshot-4](https://cloud.githubusercontent.com/assets/285658/15049519/9eb7c18e-12e6-11e6-9371-119a8bc8a327.png)

better?

**Comment by mottosso** [comment]
Looks great. :)

**Comment by mottosso** [comment]
@tokejepsen, @mkolar and @BigRoy what do you think?

How clear is it now that an item is unchecked?

**Comment by tokejepsen** [comment]
Great work @larsbijl :smile:

**Comment by larsbijl** [comment]
![screenshot-5](https://cloud.githubusercontent.com/assets/285658/15049716/c0d8e558-12e7-11e6-8d9d-47cd8dee6e06.png)

**Comment by BigRoy** [comment]
@mottosso @larsbijl This is looking sweet!

Is the disabled state (whether you can toggle it) slightly to similar to enabled state? It's a subtle difference now. I like it, but is it obvious to a newcomer?

**Comment by larsbijl** [comment]
user testing is showing me it is to subtle. i'll have a other stab at it

**Comment by mottosso** [comment]
Some inspiration; it's temporal and will stop animating once finished, but if you're quick you can catch it. :)

- https://ci.appveyor.com/project/mottosso/pyblish/build/160

It shows:

- Several tasks
- A color for each, white means not started, yellow is running and red/green is finished
- No checkboxes

**Comment by larsbijl** [comment]
looks nice. but then we need 2 objects. because being able to disable/enable items is important.

**Comment by larsbijl** [comment]
![screenshot-6](https://cloud.githubusercontent.com/assets/285658/15055132/df8b4ba6-1302-11e6-9a4b-e0036b6d1a35.png)

seems a little better this.

**Comment by mottosso** [comment]
How about no box; and color the text instead?

**Comment by BigRoy** [comment]
@larsbijl that looks great to me.
@mottosso maybe maybe. Bit different but could be clearer?

**Comment by mottosso** [comment]
Maybe what we're heading towards is this.

Yellow is running.

![image](https://cloud.githubusercontent.com/assets/2152766/15055467/af79ba68-1304-11e6-8fb1-4582e311b842.png)

Or this?

![image](https://cloud.githubusercontent.com/assets/2152766/15055503/deec53fa-1304-11e6-84b6-8335531784d0.png)

Or this?

![image](https://cloud.githubusercontent.com/assets/2152766/15055530/0837f336-1305-11e6-83b7-b44f12841ba2.png)

Or this?

Blue is running, none is todo.

![image](https://cloud.githubusercontent.com/assets/2152766/15055563/2706da70-1305-11e6-9947-8ac932321ea6.png)

**Comment by tokejepsen** [comment]
How about colouring the text instead of having an extra indicator box?

White - Not Processed
Yellow - Processing
Green - Successful
Red - Failed

**Comment by larsbijl** [comment]
I like the last one's layout.
but with yellow for processing.

also in the example you showed the colored bar is continues. this indicates progress more the them being separated as in your example.

**Comment by mottosso** [comment]
What about if checkboxes are all that exist, until processing starts. At which point checkboxes give way to process boxes?

That could work, because there is nothing to check during or after processing, and there is no process when checking. Except for Collection, which is a special case, and can simply never have a checkbox.

**Comment by mottosso** [comment]
Here's what I mean.

![untitled-2](https://cloud.githubusercontent.com/assets/2152766/15058982/87450698-1317-11e6-9e18-cb74f6748551.gif)

**Comment by mottosso** [comment]
@larsbijl if you've got a pull-request for this, I might have a moment to take it further.

**Comment by larsbijl** [comment]
pull request submitted

**Comment by mottosso** [comment]
It was a bit more involved doing what I had in mind, and I haven't yet heard whether you guys think it's a good idea.

If you're ok with it, I'm happy to merge this as-is, because I think it's already a lot clearer.

**Comment by BigRoy** [comment]
I think this is already much better. We could always discuss additional options again later.

**Comment by mottosso** [comment]
Let's make it so!

Reference to PR.

- https://github.com/pyblish/pyblish-qml/pull/192

![untitled](https://cloud.githubusercontent.com/assets/2152766/15098787/2d3a10c6-153d-11e6-9ea3-4404fc69c8eb.gif)

**Comment by larsbijl** [comment]
lets close this ticket and create a new ticket that better reflects the changes we want to make.
