### ISSUE TITLE
plugin's that are manditory are grayed out

### ISSUE THREAD

**Issue by larsbijl** [pyblish/pyblish-qml#188]
currently when a plugin is active and not set to optional it's semi transparent.
this goes against normal conventions and gives users the idea that those are disabled or are irrelevant to there submission.

![screenshot-1](https://cloud.githubusercontent.com/assets/285658/15020277/3def85bc-1219-11e6-98b2-0b66bbaa840e.png)

maybe we can have them be fully white text but make the checkbox semi transparent so the understand it's going to run.

**Comment by mottosso** [comment]
There's nothing like a fresh pair of eyes to point out the obvious, thanks Lars!

**Comment by BigRoy** [comment]
I learned this the first day and got used to it, but definitely something that has felt off! Thanks for bringing it to the table. +1

**Comment by tokejepsen** [comment]
How would that be different from the checkboxes you are working on? https://github.com/pyblish/pyblish-qml/issues/187

**Comment by mottosso** [comment]
Good question. :S

Maybe mandatory plug-ins could have a filled/unfilled box, without check icon, instead of being greyed out?

**Comment by BigRoy** [comment]
I think this issue is regarding the text color.

With the checkboxes being grayed out I think this means the text color could stay the same? (not being more or less grey depending on whether it could be toggled?) Basically the checkbox depict it. Would that suffice? Or is it too subtle?

**Comment by larsbijl** [comment]
correct BigRoy. this was about the text color.

**Comment by tokejepsen** [comment]
With the modification to the checkbox, all white text sounds good to me :smile:

**Comment by mottosso** [comment]
> I think this issue is regarding the text color.

Yes, but wasn't it about the message greying something out is sending? Greyed out makes it seem inactive or disabled. At this point we've moved the problem to the checkbox instead, which are greyed out instead? :)
