### ISSUE TITLE
collectors have a too prominent place

### ISSUE THREAD

**Issue by larsbijl** [pyblish/pyblish-qml#189]
in the current UI we place the collectors first. this follows the workflow of pyblish well but it messes with people mental model of publishing in the following ways.

![screenshot-1](https://cloud.githubusercontent.com/assets/285658/15020862/d4c07bd4-121b-11e6-8f91-b44333e424b5.png)

we force them to look at a list of validators that are rarely what they care about. 
only when they are not seeing a object in the left hand side do we care about a collector. it also makes people believe that a lot of this information is irrelevant.

then when it comes to the other 3 stages the metal model has to change that all of them are relevant and should be inspected.
## proposed

create a accordian style menu for the right hand side where collects are by default in a closed state

![screenshot-2](http://www.cssscript.com/wp-content/uploads/2015/01/Smooth-Vertical-Accordion-Panels-with-Pure-JS-and-CSS3.jpg)

1) this reduces the overwelmed feeling users will have with some many entires in a list
2) it reduces the UI unless needed. less is more.
3) less metal context switching in what the elements in the right hand are doing.

**Comment by mottosso** [comment]
There have been talks about two separate views of plugins and instances - one of which is developer-friendly and the other artist-friendly - separated by a tab.

At the moment, it's kind of a mix; some things are helpful to a developer, but less so for the end user and vice versa.

@BigRoy recently (last week) showed interest in developing an artist-friendly view, not sure how far he got with that. Roy?

**Comment by BigRoy** [comment]
Unfortunately I haven't gotten around to investigating it more. My first look fooling around in the pyblish qml code was rather quick and I hadn't found the way to actually build it as of yet. I'm a bit busy at work at the moment, but once I can find some time on my hands this is high on my list.

I do like the idea of a "collapsable" layout, just not sure yet if this is the right place. What information would it show in its collapsed state? Something like title and amount of collectors? And what would you see if it's currently processing a plug-in in the closed accordeon area? Would it be clear to the artists that it's processing there? (Would the header blink?)

**Comment by mottosso** [comment]
> Something like title and amount of collectors? ... Would it be clear to the artists that it's processing there? (Would the header blink?)

Yes, yes and yes. :) I think so.

**Comment by morganloomis** [comment]
I like the idea of having an accordion for each of the CVEI steps, which could be collapsed by default but pop open if an error is raised to show the plugins. Each collapsed section could also double as a progress bar with text showing which plugin is being evaluated at the moment.

**Comment by tokejepsen** [comment]
This has been implemented with #275.
