### ISSUE TITLE
Instances turns green in collection

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#208]
**Description**

This is purely a cosmetic bug, so very unimportant, but wanted to report anyways.
The instances turn green, when you have instance plugins processing them in the collection stage.

![capture](https://cloud.githubusercontent.com/assets/1860085/16761863/ff5eed38-4819-11e6-9153-425efa0c9e4b.JPG)

As a developer I know why this problem occurs, but as an end-user this might be odd/confusing.

Repro case:

``` python
import pyblish.api


class CollectInstances(pyblish.api.ContextPlugin):
    """ Collects """

    order = pyblish.api.CollectorOrder

    def process(self, context):

        instance = context.create_instance(name="temp1")
        instance.data["family"] = "temp"


class AppendData(pyblish.api.InstancePlugin):
    """ Appending data """

    families = ['temp']
    # offset to piggy back from default collectors
    order = pyblish.api.CollectorOrder + 0.2

    def process(self, instance):

        instance.data["something"] = "else"
```

**Comment by tokejepsen** [comment]
This does not seem to be a problem anymore.

@mottosso could you confirm?

**Comment by mottosso** [comment]
I haven't noticed it actually, let's close this until it re-surfaces.
