### ISSUE TITLE
Missing PyQt5 for pip install

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#209]
**Description**

When installing with ```pip install pyblish-qml```, PyQt5 does not get installed.

**Expected results**

I would expect PyQt5 to be installed as a dependency, to work out-the-box.

**Short reproducible**

```
pip install pyblish-qml
python -m pyblish_qml --debug
```

**Comment by tokejepsen** [comment]
I've got a ```setup.py``` working and tested, sort of:s

```pyblish_qml``` opens with nothing in it.
![capture](https://cloud.githubusercontent.com/assets/1860085/17409381/f5100150-5a66-11e6-85ea-cd030948c8e1.PNG)

And there seems to be a problem with "QtQuick.Controls":
```
(temp) C:\Users\admin\Documents\pipeline\launch>python -m pyblish_qml --debug
Starting Pyblish..
Starting in debug-mode
Looking for server..
Listening on 127.0.0.1:9090
No existing server found, creating..
Debug server created successfully.
Running mocked RPC server @ 127.0.0.1:6000
Listening on 127.0.0.1:6000Settings:

  WindowTitle = Pyblish (DEBUG)
  ContextLabel = World
  WindowSize = (430, 600)
Entering state: "hidden"
Entering state: "ready"
Entering state: "clean"
Entering state: "alive"
Awaited statemachine for 0.00 ms
Entering state: "visible"
Entering state: "initialising"
Spent 1204.00 ms creating the application
file:///C:/Users/admin/Documents/pipeline/miniconda/envs/temp/lib/site-packages/
pyblish_qml/qml/app.qml:9:1: module "QtQuick.Controls" version 1.3 is not instal
led
INFO - Collecting Negatron
INFO - Selecting instances..
INFO - Selecting: Peter01
INFO - Selecting: Richard05
INFO - Selecting: Steven11
INFO - Selecting: Piraya12
INFO - Selecting: Marcus
INFO - Selecting: Extra1
INFO - Selecting: DependencyInstance
INFO - Selecting: NoFamily
INFO - Selecting: Failure 1
WARNING - I'm good
INFO - Selecting: Failure 2
WARNING - I'm about to fail
INFO - Sleeping for 2 seconds..
INFO - Good morning
INFO - Reversing instances in the context..
INFO - Reversed!
INFO - Collecting Positron
Spent 2528.00 ms resetting
Made 19 requests during publish.
Spent 2825.00 ms resetting
Made 25 requests during reset.
Entering state: "ready"
```
Is it to do with ```python-qt5``` on PyPI not being up to date?

**Comment by mottosso** [comment]
python-qt is Windows only, so we can't use that for a dependency.

We could use `pip install PyQt5`, but it only exists on PyPI for Python 3.5, so we can't use this either.

**Comment by tokejepsen** [comment]
Alright, so for getting ```pyblish_standalone``` pip installable, we can live with having to assume PyQt5 to be present?

**Comment by mottosso** [comment]
Yes, I think so. So long as it is front and center in the README.

I wouldn't mind having "PyQt5" in the list of requirements though. I don't think it will do any harm on versions of Python that doesn't support it, and it will work on 3.5 today and in an increasing amount in the future. It may also make it clear that it really is a dependency.

**Comment by tokejepsen** [comment]
> I wouldn't mind having "PyQt5" in the list of requirements though

Sorry, you mean in the README or in ```setup.py```?

**Comment by mottosso** [comment]
In the setup.py
