### ISSUE TITLE
Premature client exit

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#212]
**Description**

When a client prematurely exists or gets terminated, the server gets stuck listening to a non-existing client.

This has been discussed in the forums as well; http://forums.pyblish.com/t/pyblish-standalone-exit-prematurely/267

**Expected**

The server should be able to handle unexpected client termination.

**Reproducible**

```python
import subprocess
import time


# server
p_server = subprocess.Popen(["python", "-m", "pyblish_qml"])

script = """import time
import pyblish_qml
import pyblish.api
class LongDelay(pyblish.api.ContextPlugin):

    order = pyblish.api.CollectorOrder

    def process(self, context):
        time.sleep(30)

pyblish.api.register_plugin(LongDelay)


pyblish_qml.install()
pyblish_qml.show()
try:
    while True:
        time.sleep(1)
except (KeyboardInterrupt, SystemExit):
    # Close GUI on terminal session end
    pass
"""

# client 1
p_client = subprocess.Popen(["python", "-c", script])
time.sleep(5)
p_client.kill()

# client 2
p_client = subprocess.Popen(["python", "-c", script])
```

**Solution**

Possible solution is to have a bi-direction communication, that can run asynchonous; http://forums.pyblish.com/t/pyblish-standalone-exit-prematurely/267/4?u=tokejepsen

**Comment by mottosso** [comment]
Isn't this #205?

**Comment by tokejepsen** [comment]
You are right, it is.

Should I close this and add to #205?

**Comment by mottosso** [comment]
Yes please.
