### ISSUE TITLE
module "QtQuick.Controls" version 1.3 is not installed

### ISSUE THREAD

**Issue by derrickb** [pyblish/pyblish-qml#215]
Windows 7
Python 2.7

Did the following pip installs:
`pip install python-qt5`
`pip install pyblish-qml`

Then tried:
`python -m pyblish_qml`

And get this output:
```
Spent 7330.00 ms creating the applicationListening on 127.0.0.1:9090
Entering state: "hidden"
Entering state: "ready"
Entering state: "clean"
Entering state: "alive"
```

And then the error:
`module "QtQuick.Controls" version 1.3 is not installed`
in file `pyblish_qml/qml/app.qml:9:1`

I tried following the comment in #34 and set the `QML2_IMPORT_PATH` env var but still get the error.

**Comment by mottosso** [comment]
Thanks @derrickb, it looks like you did everything right, I'm not entirely sure what went wrong.

Try the Python 3.5 distribution of PyQt5, you can use that in conjunction with Python 2 in e.g. Maya without problem.

```python
$ pip3 install PyQt5
$ pip3 install pyblish-qml
$ python3 -m pyblish_qml
```

**Comment by derrickb** [comment]
Thank you, @mottosso, but unfortunately this is for a large team where rolling out another python version is not a solution we'd be comfortable with.

**Comment by mottosso** [comment]
Then it'd be safest to compile your own version of PyQt5. You can use VS2015, it's what I've been using for python-qt. Otherwise, use the version of VS used for your version of Python.

**Comment by mottosso** [comment]
There is also a newer version if you install python-qt5 this way.

https://github.com/pyqt/python-qt5#a-install-with-pip-and-git

Alternatively, via git clone directly.

**Comment by derrickb** [comment]
> https://github.com/pyqt/python-qt5#a-install-with-pip-and-git

This method worked, thank you!

**Comment by mottosso** [comment]
Excellent, thanks for confirming!
