### ISSUE TITLE
Alert user on completion

### ISSUE THREAD

**Issue by BigRoy** [pyblish/pyblish-qml#227]
# Problem

For long publishes it often happens one minimizes the Window, yet it is never brought to attention when the processing finishes (e.g. after Validation _with_ errors or after completing a valid publish)

# Solution

Let the icon in the taskbar blink, like many applications do to hint something has happened.

# Reference

https://gitter.im/pyblish/pyblish?at=58b6e89721d548df2c76a3ee
http://www.qtforum.org/article/12285/taskbar-blink-flash.html

**Comment by mottosso** [comment]
Would you like a popup balloon to appear as well? Could also tell you whether publishing failed or succeeded.

![image](https://cloud.githubusercontent.com/assets/2152766/23466985/af768f24-fe94-11e6-85a5-208da497ceb2.png)

**Comment by BigRoy** [comment]
It could definitely. I'm wondering whether a user would only want to see that whenever the Pyblish window was "inactive" at the time of finishing? (E.g. when validating it might be done quickly)

**Comment by mottosso** [comment]
Sure, there could be a timer on it, say 10 seconds after leaving the window inactive.

**Comment by BigRoy** [comment]
Having checked with the users in our studio they think it would be a great addition to have a pop-up to become visible. Maybe just try the pop-up _whenever it is inactive_ to begin with?

**Comment by BigRoy** [comment]
Closing this to continue the balloon pop-up notification in another issue.
