### ISSUE TITLE
Selectable error logs

### ISSUE THREAD

**Issue by aardschok** [pyblish/pyblish-qml#240]
## Issue
When a validation fails I would like to be able to select the text from the error log of each failed validation.
This allows me to select filename of the module where the error occurred. This reduces the time for looking which module I need to open.

## Solution
Enable text selectable in the error log.

**Comment by mottosso** [comment]
Long standing duplicate. :) Pull-requests are welcome!

https://github.com/pyblish/pyblish-qml/issues/50
