### ISSUE TITLE
i have a question about use pyblish qml

### ISSUE THREAD

**Issue by xtvjxk123456** [pyblish/pyblish-qml#242]
yes, i know pyblish qml use pyqt5,
and i installed pyqt5 for python 2.7 alreadly.
it work well outside maya.

and i want to use pyblish qml with maya2015,is it possible(i watched some video pyblish in ftrack,that pyblish qml can run from maya2016)?

please help me

**Comment by mottosso** [comment]
Yes, it can run on all versions of Maya from 2013-2018.
