### ISSUE TITLE
is it right?

### ISSUE THREAD

**Issue by xtvjxk123456** [pyblish/pyblish-qml#243]
![image](https://user-images.githubusercontent.com/8720281/28654048-eb4f9498-72c3-11e7-9267-9251830eae50.png)

in maya 2016
pyblish qml use mayapy(2.7.6),although i alreadly set PYBLISH_QML_PYTHON_EXECUTABLE env (2.7.3)

is it right??

**Comment by mottosso** [comment]
That looks right, good job!
