### ISSUE TITLE
Pyblish QML causing Maya to freeze when Charcoal Editor is loaded

### ISSUE THREAD

**Issue by xtvjxk123456** [pyblish/pyblish-qml#244]
(pyblish qml work well in standalone python console)

![image](https://user-images.githubusercontent.com/8720281/28664327-aae0b3cc-72f2-11e7-92bb-3626d6222901.png)

not working in maya 2015,
(env has set alreadly)
![image](https://user-images.githubusercontent.com/8720281/28663800-fa4131c8-72f0-11e7-9f0a-8aae302dbfa5.png)

the code(in maya script editor):
```
import sys
sys.path.append(r'C:\Python27\Lib\site-packages')

from pyblish_qml import api
api.install()
api.show()

```
will make maya2015 crash (or hang on)
![image](https://user-images.githubusercontent.com/8720281/28664040-a646b4fc-72f1-11e7-9172-82046f165652.png)

please help.

**Comment by mottosso** [comment]
Hi @xtvjxk123456,

I'm having trouble reading that last image, but I spot ` QtGui4.dll` which tells me it's trying to use PyQt4. This is a problem with your paths.

Try removing these lines.

```python
import sys
sys.path.append(r'C:\Python27\Lib\site-packages')
api.install()
```

So you end up with only this.

```python
import pyblish_qml
pyblish_qml.show()
```

- [Reference](https://github.com/pyblish/pyblish-qml#usage)

And remove `PYBLISH_QML_PYQT5`, this is only needed if the Python you use is not able to find PyQt5 on it's own, but it looks like the Python you use has PyQt5 installed for it, so this isn't necessary.

You say it works from your terminal, in that case you shouldn't need any additional variables. Try this.

```bash
$ python -m pyblish_qml
```

If this works, then from the same terminal, launch Maya.

```bash
$ c:\path\to\maya.exe
```

Finally, if none of that works, try removing your Maya preferences to make sure there isn't anything interfering with the launch.

**Comment by xtvjxk123456** [comment]
first:
![image](https://user-images.githubusercontent.com/8720281/28665203-811b945a-72f5-11e7-9335-e25181a878a0.png)
no pth in maya site_packages dir

second:
![image](https://user-images.githubusercontent.com/8720281/28665243-a383d64c-72f5-11e7-8ba2-8f6a35cf4abe.png)
no useless env data (my company pipeline script)

third:
![image](https://user-images.githubusercontent.com/8720281/28665285-c57a6ec8-72f5-11e7-8d3d-2d7e85f1c7dd.png)
start maya ,and my sys.path is above

fourth:
![image](https://user-images.githubusercontent.com/8720281/28665471-5694748a-72f6-11e7-8147-28452fb2a7fb.png)
(i delete the env PYBLISH_QML_PYQT5)

then i write code in maya script editor(pyblish_qml not in sys.path):
```
import sys
sys.path.append(r'C:\Python27\Lib\site-packages')
import pyblish_qml
pyblish_qml.show()
```

and crash(or hang on).....
what a desperate things.

**Comment by xtvjxk123456** [comment]
by the way,
`python -m pyblish_qml`
work well

**Comment by mottosso** [comment]
Thanks for the images, that's really great.

You showed me your `site-packages` from Maya, but you're adding a different `site-packages` from `Python27`. Could you try removing this one:

```python
import sys
sys.path.append(r'C:\Python27\Lib\site-packages')
```

It might not be the cause, it just makes it easier for me to see that there can't be anything in that folder causing issues. Like if you had another install of PyQt4 in there.

**Comment by mottosso** [comment]
Next, could you tell me when it crashes? Before or after the GUI appears? What happens to the GUI, is it still responsive?

**Comment by xtvjxk123456** [comment]
yes ,in `'C:\Python27\Lib\site-packages'` there is a pyqt4 module
![image](https://user-images.githubusercontent.com/8720281/28665831-901178b0-72f7-11e7-8c66-a8747d6d92d3.png)

**Comment by xtvjxk123456** [comment]
after the GUI appears, maya crash(or hang on)

**Comment by mottosso** [comment]
> yes ,in 'C:\Python27\Lib\site-packages' there is a pyqt4 module

Ok, that might not be the cause of this issue, but it can cause problems elsewhere, especially since you also have PySide in there as it would override the PySide used natively by Maya. But that is a separate issue.

> after the GUI appears, maya crash(or hang on)

Ok, if the the Pyblish QML GUI appears and Maya freezes then it could be one of your plug-ins. Could you make sure there are no plug-ins running, and try again? Could you show me what plug-ins you have running currently?

It could happen, for example, if one of your plug-ins causes an infinite loop and never finishes.

**Comment by xtvjxk123456** [comment]
![image](https://user-images.githubusercontent.com/8720281/28666128-afab5668-72f8-11e7-827f-29dfcba199de.png)

!!!! after i unload 'charcoalEditor',
my god,
it works!
it works!!!
it works!!!!!

**Comment by xtvjxk123456** [comment]
why?

**Comment by mottosso** [comment]
That is a good question!

**Comment by xtvjxk123456** [comment]
so,what is next?
(always unload that .mll or what else?)

**Comment by mottosso** [comment]
Did you try removing `C:\Python27\Lib\site-packages` from your `sys.path`?

**Comment by xtvjxk123456** [comment]
no ,because when i start maya ,maya can find pyblish_qml if  `C:\Python27\Lib\site-packages` no  in sys.path

**Comment by mottosso** [comment]
Ok, now I think we're getting somewhere.

When installing Pyblish QML for Maya, it's important you install it only for Maya. You can keep it installed at `C:\Python27`, but you shouldn't use this in Maya.

What you can do is either (1) install it into the `site-packages` of Maya, e.g. `C:\Program Files\Autodesk\Maya2015\Python\Lib\site-packages`, or preferably (2) install it anywhere and add that path to your `sys.path`.

**Example**

```bash
$ cd c:\pyblish
$ pip install pyblish-qml --target .
$ set PYTHONPATH=%cd%
$ maya
```

This way, Maya will have access to it, but not any of your other Python 2.7 libraries. It's a very bad idea to expose Maya to those, especially if they are compiled like PySide and PyQt, as Maya is using a unique version of Python 2.7 that can cause obscure problems with libraries compiled for another Python, like the one you are seeing here.

**Comment by xtvjxk123456** [comment]
i find that as long as **do not run** code in `charcoal editor` ,everything is ok even i alreadly load `charcoal editor.mll`

**Comment by xtvjxk123456** [comment]
I'll do what you tell me

**Comment by mottosso** [comment]
That is a tough one, thanks for your patience on this!

I don't have Charcoal available here, but what I would have a look at is whether launching the editor in any way modifies [`utils.executeInMainThreadWithResult`](https://github.com/pyblish/pyblish-qml/blob/80562ac9f3507bc09fed9b00e78f13dbe715fba1/pyblish_qml/host.py#L221). It's a very slim chance, but I can't see how it otherwise could affect QML. This function is used to run plug-ins, and it's possible Charcoal has modified or overridden it in some way.

Try something like this.

```python
from maya import util, mel
before = utils.executeInMainThreadWithResult
mel.eval("charcoal editor")
after = utils.executeInMainThreadWithResult
if before == after:
  print("Nothing is wrong here")
```

**Comment by xtvjxk123456** [comment]
![image](https://user-images.githubusercontent.com/8720281/28667634-f346d52c-72fe-11e7-99e5-23406c3aefac.png)

**Comment by xtvjxk123456** [comment]
Thank you so much for your assistance.
i Learned a lot.

i think it is time to close this issue
Thank you again

**Comment by mottosso** [comment]
Yes, sorry I'm not sure what it could be.. If you find it, please do let me know and I'll try and find a solution for it.

**Comment by xtvjxk123456** [comment]
i will,
Thank you again

**Comment by mottosso** [comment]
Heard from the developer on this just now.

> The most recent update to Charcoal Editor 2 (v2.5.4) should fix this reported Pyblish issue:

Once that's confirmed we can lay this issue to rest. :)
