### ISSUE TITLE
Plug-ins not appearing

### ISSUE THREAD

**Issue by xtvjxk123456** [pyblish/pyblish-qml#245]
i remember when pyblish_qml find PYBLISHPLUGINPATH, it show information in maya script editor.
but pyblish_qml can not find it anymore 
![image](https://user-images.githubusercontent.com/8720281/28701195-0f6b908e-7387-11e7-9b15-8d4c15a3b7ec.png)

![image](https://user-images.githubusercontent.com/8720281/28701198-12894b80-7387-11e7-8814-ca44f1bf057f.png)
is it a bug? or my system bug?

**Comment by mottosso** [comment]
This should work. There are a few things you can to do debug this.

1. Increase logging to see whether some plug-ins were skipped, e.g. from syntax errors
   ```python
import logging
logging.getLogger("pyblish").setLevel(logging.DEBUG)
```
2. Register plug-ins by hand, they should appear
   ```python
from pyblish import api

class MyPlugin(api.ContextPlugin):
  order = api.CollectorOrder

api.register_plugin(MyPlugin)

import pyblish_qml
pyblish_qml.show()
```
3. See what variables Maya can see
   ```python
import os
print(os.environ["PYBLISHPLUGINPATH"])
```
4. List plug-ins from Pyblish, these should match what you see in Pyblish QML
   ```python
from pyblish import api
print(api.discover())
```

Pyblish QML isn't the one actually seeing your plug-ins, the host application (e.g. Maya) is. Pyblish QML is simply the graphics running on-top of Maya that is the one seeing and running the plug-ins. So make sure Maya can see it, and you should be golden.

**Comment by xtvjxk123456** [comment]
sorry ,it is my mistake
i write a plugin has same classname with other plugin, 
pyblish do not load Duplicate plug-in

Thank you !

**Comment by xtvjxk123456** [comment]
i want to close this issue,
all right?
