### ISSUE TITLE
host or hosts?

### ISSUE THREAD

**Issue by xtvjxk123456** [pyblish/pyblish-qml#246]
![image](https://user-images.githubusercontent.com/8720281/28710230-d41b6b24-73b5-11e7-8e17-1f93f8b8f957.png)

It's a confusing thing
host or hosts?
i found pyblish_qml only show plugin when use host.

The same situation ,as well as family and families

**Comment by mottosso** [comment]
Make sure you're run through http://learn.pyblish.com and I think it'll make more sense.

**Comment by xtvjxk123456** [comment]
i am sure "hosts" not work
