### ISSUE TITLE
pyblish_qml current host??

### ISSUE THREAD

**Issue by xtvjxk123456** [pyblish/pyblish-qml#248]
![image](https://user-images.githubusercontent.com/8720281/28763976-8af733b0-75f4-11e7-9560-720578501ed4.png)

e...it is right??
(use pyblish.api.current_host() in plugin class ,and plugin load use env PYBLISHPLUGINPATH)

that mean i must write  and register plugin in maya?

**Comment by mottosso** [comment]
You can register a host using `api.register_host("my_host")`, which is just a plain string. Or you can have the host registered with [Pyblish Maya](https://github.com/pyblish/pyblish-maya).

@xtvjxk123456 For general questions about Pyblish, it'd be best if you posted on the [forums](http://forums.pyblish.com/) and save issues for bug reports.

- http://forums.pyblish.com

**Comment by xtvjxk123456** [comment]
ok, i will do it ,
Thanks
