### ISSUE TITLE
Hyperlinks in Output

### ISSUE THREAD

**Issue by davidmartinezanim** [pyblish/pyblish-qml#25]
I think that it would be nice if the output panel had some kind of rich formatting.

I don't think that we need anything overly complex. Having said that it would be great if any URLs are converted into hyperlinks that can be clicked (triggering default browser and such).

When a Publish fails, I want to provide the artist not only with a message but a link to a WIKI page explaining what needs to be done to get the plugin to succeed. This kind of training is specially useful for new starters that are not familiar with the pipeline.

I other words, it would help us *empowering* artists.

**Comment by tokejepsen** [comment]
Heres a preview of a working version of this;

![capture](https://cloud.githubusercontent.com/assets/1860085/12151047/0085e59e-b4a5-11e5-841f-0e7e46301019.PNG)

The blue links are generated by html code in the text;
```html
<a href="http://pyblish.com/">click here</a>
```

And the white links are generate automatic from recognizing a "http" pattern.

**Comment by mottosso** [comment]
Woot woot! Great work!
