### ISSUE TITLE
sorry, i got a error

### ISSUE THREAD

**Issue by xtvjxk123456** [pyblish/pyblish-qml#250]
I'm sorry to trouble you,

pyblish_qml suddenly stopped working,
i can not figure out what is it.
please help!

![image](https://user-images.githubusercontent.com/8720281/28960248-6a56d310-7930-11e7-9c5b-4e41ff9a93bf.png)

**Comment by xtvjxk123456** [comment]
i wirte a plugin about query a window service's status before first time occur this error,
use pywin32

**Comment by xtvjxk123456** [comment]
my plugin is problem....It's such a shame
sorry to open this issue,
i will close it
but i think pyblish_qml is Not very stable somehow.

**Comment by mottosso** [comment]
Happy to hear you solved it.

For your next issue, could I ask that you make the title a little more descriptive? Think of it like a title of a blog post. Other people, including myself, browsing through issues should ideally have some idea of what each issue is about from just the title.
