### ISSUE TITLE
More accurate statuses.

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#274]
**Motivation**

The status text in the footer of the overview should show which stage the processing is at.

Display each of the CVEI stages; ```Collecting...```, ```Validating...```, ```Extracting...```, ```Integrating...```.
Display when each stage is finished; ```Finished collection.```, ```Finished validation.```, ```Finished extraction.```, ```Finished integration.```.

**Comment by BigRoy** [comment]
With #273 artists have mentioned that "Finished.." with the dots behind it was slightly confusing because they imagined it being finished then, but still busy doing something. The dots gave the idea that it's still doing something.
