### ISSUE TITLE
Instances with same family under separate group

### ISSUE THREAD

**Issue by asztalosdani** [pyblish/pyblish-qml#279]
### Description
I have two collectors that return instances with same family. On the GUI it is shown under separate group.
![image](https://user-images.githubusercontent.com/9664767/36846882-b96794dc-1d5c-11e8-80a1-4efe418e5b67.png)
Clicking on the family group toggles both of the instances.
Further investigation revealed, it occurs if an instance with another family is created between the two instances with common family.

### Expected result
They should be placed under one group.
### How to reproduce
Please note the order and the family of the plugins.
```python
import pyblish.api
class ACollector(pyblish.api.ContextPlugin):
    order = pyblish.api.CollectorOrder - 0.1
    def process(self, context):
        context.create_instance("A instance", family="common_family")
        
class BCollector(pyblish.api.ContextPlugin):
    order = pyblish.api.CollectorOrder
    def process(self, context):
        context.create_instance("B instance", family="another_family")
        
class CCollector(pyblish.api.ContextPlugin):
    order = pyblish.api.CollectorOrder + 0.1
    def process(self, context):
        context.create_instance("C instance", family="common_family")

pyblish.api.register_plugin(ACollector)
pyblish.api.register_plugin(BCollector)
pyblish.api.register_plugin(CCollector)

```

**Comment by mottosso** [comment]
Thanks @asztalosdani, this is actually the intended and expected behaviour. The instances are sorted in the order they are run.

If you add the two instances to the `context` one after the other, they will appear in the expected order. You can also add a collector at the end of your collectors that explicitly sort them, if you want.

**Comment by tokejepsen** [comment]
Here is an example of sorting the context: http://forums.pyblish.com/t/solved-collection-sorting/189
