### ISSUE TITLE
Toggling family groups

### ISSUE THREAD

**Issue by asztalosdani** [pyblish/pyblish-qml#281]
### Description
Clicking on the family gives unexpected results. See attached gif.
![pyblish_qml](https://user-images.githubusercontent.com/9664767/36964268-616f6ef6-2056-11e8-9681-7955e38a3c0b.gif)
### Expected result
1. The group should only uncheck instances if all of them are checked, and check all unchecked ones.
2. Or a proper tri-state checkbox could be implemented.
### How to reproduce
```python
import pyblish.api
class ACollector(pyblish.api.ContextPlugin):
    order = pyblish.api.CollectorOrder - 0.1
    def process(self, context):
        context.create_instance("A instance", family="family")
        context.create_instance("B instance", family="family")
        
pyblish.api.register_plugin(ACollector)
```
1. Uncheck an instance.
2. Click the family -> the unchecked instance is checked.
3. Uncheck both instances.
4. Click the family -> nothing happens
5. Check both instances.
6. Click the family -> nothing happens

**Comment by mottosso** [comment]
Thanks for these detailed reports, @asztalosdani.

I'm also noticing there is a missing icon on the Pyblish window, any idea what that could be?

**Comment by asztalosdani** [comment]
> I'm also noticing there is a missing icon on the Pyblish window, any idea what that could be?
No, not yet. The icon file is there, and pyblish_qml is reading it from the correct place.
