### ISSUE TITLE
Unchecked instances visually unclear

### ISSUE THREAD

**Issue by BigRoy** [pyblish/pyblish-qml#283]
### Issue

Not sure where this got introduced, but in the latest version of Pyblish QML unchecked instances are visually hard to read because the checkbox remains a fully solid checked state.

![worse](https://user-images.githubusercontent.com/2439881/37726470-b7a41b5a-2d35-11e8-833d-63b7270c0da5.png)

In this image the `cameraDefault` instance is actually disabled, it's clicked to be deactivated. 

The only hint that visualizes it is disabled is the darker greyed out text. 

Previously it would also clear the solid contents of the checkbox and keep only the border, which visually made much more sense.

### Proposal

Remove the solid checked color when deactivated, like:

![better](https://user-images.githubusercontent.com/2439881/37726541-ea4ef2d2-2d35-11e8-8a63-9c9919791e93.png)

---

Could be from [this change](https://github.com/pyblish/pyblish-qml/pull/277/commits/63c55d3384644e3d2733dcc583ae6308410c8d95) which was [shown here](https://github.com/pyblish/pyblish-qml/pull/277#issuecomment-352383187).

**Comment by mottosso** [comment]
How come it is green? Need reproducible.

**Comment by BigRoy** [comment]
> How come it is green? Need reproducible.

Actually, good question.

```python
import pyblish.api as api

api.deregister_all_paths()
api.deregister_all_plugins()

class CollectorA(api.ContextPlugin):
    order = api.CollectorOrder
    
    def process(self, context):
        instance = context.create_instance("A")
        instance.data["families"] = ["A"]

class CollectorPass(api.ContextPlugin):
    order = api.CollectorOrder + 0.1
    
    def process(self, context):
        pass
        
api.register_plugin(CollectorA)
api.register_plugin(CollectorPass)
```

The above stays white. 

### Odd scenario (Likely from backwards compatibility conversion?)

Now on the CollectorPass change the second argument of the `process` method to `instance`. It will still run over the context, since it's a `ContextPlugin` yet it will now start turning the Instance green.

## Use case: InstancePlugin in Collector range

We sometimes use a Collector that does some additional collecting on instances of a specific family - in those cases it will *always* turn green. Example code:

```python
import pyblish.api as api

api.deregister_all_paths()
api.deregister_all_plugins()

class CollectorA(api.ContextPlugin):
    order = api.CollectorOrder
    
    def process(self, context):
        instance = context.create_instance("A")
        instance.data["families"] = ["A"]

class CollectorA2(api.InstancePlugin):
    order = api.CollectorOrder + 0.1
    
    def process(self, instance):
        instance.data["additionalData"] = 1
        
api.register_plugin(CollectorA)
api.register_plugin(CollectorA2)
```

---

So that's two cases.

**Comment by BigRoy** [comment]
@tokejepsen @mottosso what do you believe is the intended result in the above cases?

**Comment by mottosso** [comment]
> Now on the CollectorPass change the second argument of the process method to instance.

Yes, don't do this, it's from the days of "dependency injection". ContextPlugin should only ever have `context`, and InstancePlugin should only ever have `instance`.

Sorry can't look closer at the moment but will try in the coming days.

**Comment by BigRoy** [comment]
> Yes, don't do this, it's from the days of "dependency injection". ContextPlugin should only ever have context, and InstancePlugin should only ever have instance.

Yup, was expecting that to be related. Then the only _real issue_ here is the latter use case I suppose.

**Comment by BigRoy** [comment]
Can anyone else confirm this issue?

I'm expecting the use case I showed above (_Use case: InstancePlugin in Collector range_) to be a valid use case where after collection the instance should not appear green.

The [fix I set up before](https://github.com/pyblish/pyblish-qml/pull/284/files) works for me, there an unchecked instance will never be highlighted green, orange or red.

**Comment by davidlatwe** [comment]
I can confirm this, just ran through the example use case above.

Also, can confirm this issue with my previous publish experiences on my plugins and instances, but didn't think too much at that time.

PR #284 seems to improve this well, that works for me, too.
