### ISSUE TITLE
Doesn't work with Nuke

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#301]
As reported by Jakub over [in the chat](https://gitter.im/getavalon/Lobby?at=5bab3cec41177e0bc7aab6bf), there's something preventing Pyblish QML from working with Nuke.

**Comment by darkvertex** [comment]
What Nuke version? I've opened the Pyblish QML GUI in Nuke no problem in Linux in the past.

**Comment by jezscha** [comment]
Hi @darkvertex thanks for question. Its windows 11.2v3. Would you mind to share your config?

**Comment by darkvertex** [comment]
It's studio stuff using Rez packages that I can't really share, sorry, but it should be possible to accomplish a working pyblish-qml with a [conda](https://conda.io/docs/index.html) environment with only Python 2.7, PyQt5, pyblish-base and pyblish-qml and using the `PYBLISH_QML_PYTHON_EXECUTABLE` env var in Nuke to point to this environment before you use or import the GUI.

It can be a shellscript/.bat that sets the good environment and passes the args straight to the python executable, it doesn't necessarily have to be a path to python.exe itself.

**Comment by mottosso** [comment]
@jezscha Have you experienced the issue on a different computer or user? Could it be something pre-existing in your particular environment? E.g. multiple Qt installs?

**Comment by jezscha** [comment]
@darkvertex I understand. But anyway thanks for the comprehension. In our setting we wish to stick to Python3.6.5, PyQt5==5.7.1 for all integrations if it would be possible. I understand Pyblish-qml in Nuke can be accomplished in Python2.7 and I have already experienced it myself. 

@mottosso I have been testing it on two machines which one of them was vanilla and no paths existed in env-vars. Also the second has been cleaned from all traces in env-vars and files and register. I am going to test it on other tomorrow so lets see.

**Comment by BigRoy** [comment]
@jezscha were you able to make progress with this the way you wanted?
