### ISSUE TITLE
Option to optionally group by arbitrary string, not only family

### ISSUE THREAD

**Issue by darkvertex** [pyblish/pyblish-qml#302]
Hello! Tell me if you think this might be a good idea:

Currently `pyblish-qml` groups instances by family. In most cases this is fine, but what if it was possible to designate an instance data member for overriding that? A "display group", if you will.

I have a few publishers which involve one or more individual mandatory publishes and then optionally can publish a number of assets or things in the scene. It's working, but I find it a bit ugly for the singular instances to be alone in their own collapsible tab. (I'd prefer if they were all together, but I don't want to give them all the same family as I have plugins to target specific families and that would defeat the purpose of targeting plugins by family.)

If I could assign them a "display group" string which would indicate what tab they'd go under, I think that would work best for such cases, and if none given, I'd expect the default present behaviour of grouping by family.

Thoughts?

**Comment by tokejepsen** [comment]
Sounds like a good feature. Maybe "category" is a better term?

**Comment by davidlatwe** [comment]
Hey @darkvertex , I made a PR for this feature to try out :)
Have a look !

**Comment by darkvertex** [comment]
@tokejepsen I agree with you, "category" sounds more proper.

@davidlatwe: Took a look and it seems perfect from my point of view. 👍

**Comment by davidlatwe** [comment]
Implemented :)
