### ISSUE TITLE
Toggling family groups does not respect mandatory Instances

### ISSUE THREAD

**Issue by darkvertex** [pyblish/pyblish-qml#309]
I discovered that the feature introduced by #281 does not respect whether any of the instances in that group have `.data['optional']` set to `False`, ie "mandatory" or "non-optional" instances, which I had introduced support for as of version 1.7.4.

Toggling should not fail, but it should skip the non-optional Instances from being toggled.

**Comment by davidlatwe** [comment]
I have got this solved on my end, will make a PR after the version 1.9.0 is out !

**Comment by darkvertex** [comment]
Thanks for fixing this, @davidlatwe! :tada:
