### ISSUE TITLE
Rename utility function `async` for Python 3.7

### ISSUE THREAD

**Issue by davidlatwe** [pyblish/pyblish-qml#318]
### Problem

Running Pyblish-QML with Python 3.7 will raise `SyntaxError` because of the utility function name `async`  ([at here](https://github.com/pyblish/pyblish-qml/blob/5519d3f0898cfe0c42e7f5ef0d792c7bd73337a3/pyblish_qml/util.py#L121)) has become a keyword in Python 3.7

This issue was firstly reported at *Gitter* via Ander Anjos
. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . :point_up: [January 8, 2019 6:19 PM](https://gitter.im/pyblish/pyblish?at=5c347947bd592b2e6e6e8001)

### Discussion

Should rename the function `async` to some other name like `async_` ?

**Comment by mottosso** [comment]
Fixed! https://github.com/pyblish/pyblish-qml/releases/tag/1.9.3
