### ISSUE TITLE
Display failed message at footer when instance has error on publish

### ISSUE THREAD

**Issue by davidlatwe** [pyblish/pyblish-qml#343]
### Problem

Some of our artist saying that it's a bit confusion when there are instance got error but the footer still saying `"Published"`.

![image](https://user-images.githubusercontent.com/3357009/65164319-3d871a00-da6f-11e9-80a6-f3d4bd3f3b60.png)

### Propose

Resolving this via showing `"Publish failed.."` message at footer if there are instance has error.
I think this can be implemented without dispute, since the `CVEI` workflow should be ended without any error.

**Comment by BigRoy** [comment]
Good one! Thanks. :)

To be completely clear, the final message that was implemented with the merge of #344 is:

-  ["Published, with errors.."](https://github.com/pyblish/pyblish-qml/pull/344/commits/51dd9327335c9c8b070a830881da55dbec5b879b) 

instead of 

- "Publish failed.."
