### ISSUE TITLE
Package deploy failed

### ISSUE THREAD

**Issue by davidlatwe** [pyblish/pyblish-qml#358]
It looks like CI failed to deploy package to PyPi since `pyblish-qml>1.10.6`, and based on the error message [here](https://travis-ci.org/pyblish/pyblish-qml/builds/648744181#L3472), it was because the `pip` could not be installed due to running in Python 3.4 which is outdated.

Bumping CI's Python version in [`./travis.yml`](https://github.com/pyblish/pyblish-qml/blob/40726aed9ee0ce0e887add8de7638e9f8a1ce4ca/.travis.yml#L7) should fixes the issue. But it only take effect after merged or direct push, so pinning @mottosso to confirm this. ☺️

**Comment by mottosso** [comment]
Looks like it. You can push that fix, delete the release and then release again to re-trigger it. Since nothing was uploaded to PyPI there's no harm.

**Comment by davidlatwe** [comment]
Hmmm, not sure how to *delete the release*, but I think I will create a temporary branch from `1.11.0` and trigger a custom build from travis-ci for deploying. And another custom bulild on master branch for depolying `1.11.1`.

**Comment by mottosso** [comment]
Eeek. The GitHub UI isn't obvious in how to do it, it's here: https://github.com/pyblish/pyblish-qml/releases/tag/1.11.1

**Comment by davidlatwe** [comment]
Thanks ! Turns out I also needed to delete the tag so I can trigger the build. Phew.
And finally, both `1.11.0` and `1.11.1` are now in PyPi !

**Comment by davidlatwe** [comment]
Resolved via 17ad653, closing this now.
