### ISSUE TITLE
Feature to define custom Python folder

### ISSUE THREAD

**Issue by davidmartinezanim** [pyblish/pyblish-qml#36]
I think that it might be worth adding functionality that allows to define a custom Python folder to be used by Pyblish-QML. At the moment, it will use the system's default and there might be some instances in which this is not desired.

Let's say that a company wants to use another version of Python as their default since much of their code base relies on it. Having another version of Python of the system is not a problem but we don't want to force people to make the one we expect the default one.

Instead, it would be good to have be able and pass a custom path for Pyblish to use. If no custom folder has been defined, then it could use the system's.

Just to make the system more flexible.

**Comment by mottosso** [comment]
Which Python to use might actually be related to your integration.

Running Pyblish as-is, is a matter of calling `python`, along with it's executable.

```cmd
$ python pyblish_qml\app.py
```

Which Python is actually being used depends on which Python is first on your `PATH` environment variable.

In the case of Pyblish for Maya, the decision is made [here][pm] in which a pure call to `python` is made, thus using whichever `python` is located first on your computers `PATH`, similar if you run the above from your system's terminal.

[pm]: https://github.com/abstractfactory/pyblish-maya/blob/master/pyblish_maya/__init__.py#L44

You can gain control over this by either modifying that line, or by inserting your custom path onto your `PATH` before launching Pyblish QML.

```python
import os
import pyblish_maya

# Make sure *your* path comes *first*
os.environ["PATH"] = r"c:\path\to\custom\Python27;" + os.environ["PATH"]
pyblish_maya.show()
```

**Comment by davidmartinezanim** [comment]
Thanks @mottosso 

I think that in my case, I'm better off modifying [this file].

Using the code in your comment would mean that any tool in maya that tries to run `python` would end up running the custom one. This is not ideal as some of the tools that we are using expect `Python 2.6` and the custom modules/packages that we have installed on it.

I have no problem with modifying that specific file. I was just wondering if there was a flag that I should be using instead or if it was worth adding.

[this file]: https://github.com/abstractfactory/pyblish-maya/blob/master/pyblish_maya/__init__.py#L44

**Comment by mottosso** [comment]
> Using the code in your comment would mean that any tool in maya that tries to run python would end up running the custom one.

You can restore the `PATH` after you've used it. Have a look at the modified code above.

If you still would like to modify the file, I would suggest making your own wrapper so that you don't lose out on being able to update the library afterwards.

**pyblish_maya_wrapper.py**

```python
from pyblish_maya import *

def show(console=True):
    if not GUI:
        raise ValueError("No GUI registered")

    if not "ENDPOINT_PORT" in os.environ:
        raise ValueError("Pyblish start-up script doesn't seem to "
                         "have been run, could not find the PORT variable")

    host = "Maya"
    port = os.environ["ENDPOINT_PORT"]

    CREATE_NO_WINDOW = 0x08000000
    proc = subprocess.Popen([r"c:\path\to\custom\Python27\python.exe", "-m", "pyblish_qml.app",
                             "--host", host,
                             "--port", str(port)],
                            creationflags=CREATE_NO_WINDOW if not console else 0)

    # Kill child process on Maya exit
    def kill_child():
        proc.kill()

    atexit.register(kill_child)
```
