### ISSUE TITLE
Pyblish QML is unresponsive when opening another file in Blender

### ISSUE THREAD

**Issue by jasperges** [pyblish/pyblish-qml#360]
When you open a file in Blender all running modal operators are cancelled. So when Pyblish QML is running, the modal operator responsible for the communication between Blender and Pyblish is also cancelled. This effectively renders Pyblish QML unrepsonsive.

A possible fix would be to quit Pyblish QML when the operator is cancelled. That could be done from the [`cancel` method of the operator](https://github.com/pyblish/pyblish-qml/blob/master/pyblish_qml/host.py#L676-L678). I guess we need to send a function to Pyblish QML with `blender_to_qml.put()`. But I'm not sure what to send. Any ideas? And maybe there are better ways to tackle this problem.

**Comment by mottosso** [comment]
Not 100% sure how Blender's operators works, but it looks like one is [registered here](https://github.com/pyblish/pyblish-qml/blob/master/pyblish_qml/host.py#L681) which may indicate there is an unregistration where we could do things?

Otherwise, it's a class, so perhaps the `__del__` operator is called on deletion?

In each case, it looks like the operator's `cancel()` is the one to call.

**Comment by jasperges** [comment]
When you open a file the operator is cancelled and then `cancel()` of the operator is called. This already happens.
As mentioned my proposal is to send some sort of 'quit' or 'closeWindows' signal to Pyblish QML so it closes instead of staying open and being unresponsive.
But how can we send that signal from the operator's `cancel()`?

**Comment by mottosso** [comment]
Ah I see what you mean.

The way hosts like Blender speak to QML is via a "proxy", that looks [like this](https://github.com/pyblish/pyblish-qml/blob/18826c8cad919b61e2c5332055242f85db814fd6/pyblish_qml/ipc/server.py#L35). You can find it in:

```py
from pyblish_qml import api
proxy = api.current_server()
proxy.quit()
```

**Comment by jasperges** [comment]
Looking from the code I could simplify it to just `quit()`, because we're in `hosts.py`.
Works like a charm. No more unresponsive Pyblish QML.
