### ISSUE TITLE
Add save settings functionality to the GUI

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#54]
> @davidmartinezanim opened this issue 8 days ago in https://github.com/pyblish/pyblish/issues/154

It would be good if the GUI stored settings such as it's size and placement within the screen. Ideally, we want that to happen automatically when the window is moved/resized.

We don't want users to keep moving and resizing the interface every time it is opened.

**Comment by davidmartinezanim** [comment]
Also, I'm finding myself moving it to my second monitor and resizing every time I run it. :-)

I don't think that the second monitor is going to be an issue as it is a different value of coordinates. Having said that, we will need a way to reset to default position/size. In my experience, when people move to another desk or change computers, Windows gets confused about which screen is which and applications end up opening in a screen that does not exist (For example in negative coordinates)

**Comment by mottosso** [comment]
Implemented in 0.2.6 :)

I'm aware that it doesn't last across sessions. Let's keep that in mind a future release.
