### ISSUE TITLE
Visualise path to plug-in

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#55]
# Goal

As suggested by @davidmartinezanim, include a path to plug-ins so they are easier to find in case maintenance is required.

Perhaps in the property panel?

**Comment by davidmartinezanim** [comment]
> Perhaps in the property panel?

Sounds good to me. I would make it a link or have the option to open that file in the file explorer (for quick access)

**Comment by mottosso** [comment]
Implemented in 0.2.6
