### ISSUE TITLE
Splash Screen

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#6]
### Goal

To provide users with a sense of immediate feedback.

Currently, the GUI is very small, yet it takes about 2 seconds for anything to appear on screen (Windows, on Ubuntu the time is half that for some reason).

### Architecture

Utilise the feature of QML which allows for components to be dynamically loaded so as to allow light items to appear first, keeping the user company, while the rest of the GUI is computed and finally displayed. Once the component has been loaded, listen in on the signal and from there trigger the animation to "unfold" the interface.

### User Interface

Provide part of the final interface as something for the user to look at while awaiting full functionality.

![issue6-splash](https://cloud.githubusercontent.com/assets/2152766/5030552/77227782-6b48-11e4-81d0-6fcc00217223.gif)

**Comment by tokejepsen** [comment]
We have this now, right?

**Comment by mottosso** [comment]
That is true, the initial problem was solved by pre-loading.
