### ISSUE TITLE
Logging filter in the terminal tab

### ISSUE THREAD

**Issue by davidmartinezanim** [pyblish/pyblish-qml#61]
Do you think it would be worth to add an option to filter the different logging levels?

Some of the plugins I'm doing print the current file being validated and the scenes have a lot of those. When I want to focus on the errors, it kind of clutters the view as I get all the info logs. Having said that, they are useful when it comes to make sure that the plugin is going through all of those.

**Comment by mottosso** [comment]
Implemented in 0.2.7
