### ISSUE TITLE
WindowsError

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#70]
This happened on a machine running Windows when trying to launch the GUI.

```
# Traceback (most recent call last):
#   File "<maya console>", line 2, in <module>
#   File "C:\Program Files\Autodesk\Maya2013\bin\python26.zip\subprocess.py", line 650, in __init__
#     errread, errwrite)
#   File "C:\Program Files\Autodesk\Maya2013\bin\python26.zip\subprocess.py", line 855, in _execute_child
#     startupinfo)
# WindowsError: [Error 2] The system cannot find the file specified #
```

And was due to having had Python previously installed, and then removed. Unsure about whether or not it happens if Python was never installed.

This should produce the error.

```python
import subprocess
subprocess.Popen(["python"])
```

Once way of solving the problem is to re-install Python.

**Comment by tokejepsen** [comment]
Pretty sure this is error the I get when the machines Python isn't setup correctly. So the two cases I found this was wrong Python version installed, and PATH environment variable pointing to a wrong Python version.

**Comment by tokejepsen** [comment]
In both cases its was Python 2.6 previously installed. Uninstalling Python 2.6 and installing Python 2.7 worked on one machine.
On the other machine the environment variable to the "Python26" was still present, and the files weren't completely removed. Probably because some processes were still running while uninstalling.

**Comment by mottosso** [comment]
Cool. Were you running from Maya too?

**Comment by mottosso** [comment]
I got this again in an unrelated circumstance, by simply not having access to Python on the machine and running subprocess from within Maya. Maya must not be including or exposing part of the Python library required for subprocess to function.
