### ISSUE TITLE
Commenting and "Are you sure?"

### ISSUE THREAD

**Issue by mottosso** [pyblish/pyblish-qml#9]
### Goal

Provide an option for users to enter an optional comment, may be mandatory or may never appear based on studio-wide settings.

Additionally, with or without commenting, provide for a safety; preventing users from accidentally publishing.
### User Interface

![issue9-commenting](https://cloud.githubusercontent.com/assets/2152766/5034141/e5ac71c4-6b63-11e4-87fc-db84714886a4.gif)

**Comment by tokejepsen** [comment]
Is this not implemented? We are missing the "Are you sure?" dialog, but don't see a need for it.

**Comment by mottosso** [comment]
The Are you sure? thingy is the need to click twice to publish; once to bring up the comment box (unless it's already open), and another to fire away. That fact wasn't clear enough in the description and it took a while staring at the gif to remember that's what I had in mind. :)

Whether we need it, I think not.
