### ISSUE TITLE
Would it be possible to add the context to the list of instances

### ISSUE THREAD

**Issue by davidmartinezanim** [pyblish/pyblish-qml#90]
It would be good to have a visual representation of the `context` in the GUI so it is possible to see if something has failed and stopped the publishing process.

**Comment by mottosso** [comment]
Certainly, scheduled for 0.2.10.

**Comment by davidmartinezanim** [comment]
:+1:

**Comment by mottosso** [comment]
Implemented in 0.2.10

**Comment by davidmartinezanim** [comment]
:+1:
