### ISSUE TITLE
Warning indicator

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-qml#98]
When logging warning call with `self.log.warning`, it would be nice to see an indicator in there main tab.

The suggestion is to colour the checkboxes yellow when any warnings has been logged on a plugin or instance.

**Comment by BigRoy** [comment]
Is this issue also related to the [Mechanism to warn the artist topic](http://forums.pyblish.com/t/mechanism-to-warn-the-artist/196/4) on Pyblish forums? Or would that be an additional issue since it's not only an indication but also a pause in processing?

**Comment by mottosso** [comment]
To not overwhelm this issue, I think it'd be safest to make a separate issue for the pausing as they can be added separately, and pausing is a bit more heavy weight of a change.

**Comment by tokejepsen** [comment]
This has been implemented.
